name: Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Stop service
        run: sudo systemctl stop SwagBagger.service
      - name: Publish
        run: dotnet publish SwagBagger/SwagBagger.csproj -c Release -o /home/tzer0m/Services/SwagBagger
      - name: Start service
        run: sudo systemctl start SwagBagger.service
      - name: Check status
        run: sudo systemctl status SwagBagger.service --no-pager
